### ISSUE TITLE
Error in scene-manager.ts when updating to three 0.164

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#658]
```
- Generating browser application bundles (phase: setup)...
src/managers/three-manager/scene-manager.ts(68,37): error TS2345: Argument of type '{ glyphs: { ο: { x_min: number; x_max: number; ha: number; o: string; }; S: { x_min: number; x_max: number; ha: number; o: string; }; "\u00A6": { x_min: number; x_max: number; ha: number; o: string; }; "/": { x_min: number; x_max: number; ha: number; o: string; }; ... 203 more ...; η: { ...; }; }; ... 10 more ...; u...' is not assignable to parameter of type 'FontData'.
  Types of property 'glyphs' are incompatible.
    Type '{ ο: { x_min: number; x_max: number; ha: number; o: string; }; S: { x_min: number; x_max: number; ha: number; o: string; }; "\u00A6": { x_min: number; x_max: number; ha: number; o: string; }; "/": { x_min: number; x_max: number; ha: number; o: string; }; ... 203 more ...; η: { ...; }; }' is not assignable to type 'Record<string, { ha: number; x_min: number; x_max: number; o: string; }>'.
      Property '" "' is incompatible with index signature.
        Property 'o' is missing in type '{ x_min: number; x_max: number; ha: number; }' but required in type '{ ha: number; x_min: number; x_max: number; o: string; }'.
```

**Comment by EdwardMoyse** [comment]
`FontData` was introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69203

**Comment by EdwardMoyse** [comment]
Okay, this might be fixed in @types/three@0.165.0.

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69506#discussioncomment-9305539

**Comment by EdwardMoyse** [comment]
Will close this for now, and try again once 0.165 is out.
